import { ExternalLink } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import DataTable from '@/components/ui/DataTable.jsx';
import { integer, money, number, percent, shortTime } from '@/utils/format.js';

const columns = [{ key: 'rank', label: 'Rank', render: row => <span className="font-semibold text-slate-500">#{row.rank}</span> }, { key: 'symbol', label: 'Symbol', render: row => <button type="button" className="text-left font-semibold text-indigo-600 hover:underline dark:text-indigo-300" onClick={() => window.location.assign(`/stock/${encodeURIComponent(row.tradingSymbol)}`)}>{row.tradingSymbol}<span className="block text-[11px] font-normal text-slate-500">{row.companyName || row.symbol}</span></button> }, { key: 'ltp', label: 'LTP', sortable: true, render: row => money(row.ltp) }, { key: 'changeValue', label: 'Change', sortable: true, render: row => <span className={row.changeValue >= 0 ? 'text-emerald-600' : 'text-rose-600'}>{row.changeValue >= 0 ? '+' : ''}{number(row.changeValue)}</span> }, { key: 'changePercent', label: 'Change %', sortable: true, render: row => <span className={row.changePercent >= 0 ? 'font-bold text-emerald-600' : 'font-bold text-rose-600'}>{percent(row.changePercent)}</span> }, { key: 'volume', label: 'Volume', sortable: true, render: row => integer(row.volume) }, { key: 'tradedValue', label: 'Traded Value', sortable: true, render: row => money(row.tradedValue) }, { key: 'highPrice', label: 'High', sortable: true, render: row => money(row.highPrice) }, { key: 'lowPrice', label: 'Low', sortable: true, render: row => money(row.lowPrice) }, { key: 'weekHigh52', label: '52W High', sortable: true, render: row => money(row.weekHigh52) }, { key: 'weekLow52', label: '52W Low', sortable: true, render: row => money(row.weekLow52) }, { key: 'updatedAt', label: 'Updated', render: row => shortTime(row.updatedAt) }];
export default function MarketTable({ rows, sort, setSort }) { const navigate = useNavigate(); const sorted = [...rows].sort((a,b) => { if (!sort.key) return 0; const av=a[sort.key], bv=b[sort.key]; if (av===bv) return 0; if (av==null) return 1; if (bv==null) return -1; return (av>bv?1:-1)*(sort.direction==='asc'?1:-1); }); const onSort = key => setSort(current => current.key===key ? { key, direction: current.direction==='asc'?'desc':'asc' } : { key, direction:'desc' });
  const columnsWithNavigation = columns.map(column => column.key === 'symbol' ? { ...column, render: row => <button type="button" className="text-left font-semibold text-indigo-600 hover:underline dark:text-indigo-300" onClick={() => navigate(`/stock/${encodeURIComponent(row.tradingSymbol)}`)}>{row.tradingSymbol}<span className="block text-[11px] font-normal text-slate-500">{row.companyName || row.symbol}</span><ExternalLink size={12} className="ml-1 inline" aria-hidden="true" /></button> } : column);
  return <DataTable columns={columnsWithNavigation} rows={sorted} sort={sort} onSort={onSort} getRowKey={row => row.token || row.tradingSymbol} emptyMessage="No market rows available." />; }
