import { Activity, BarChart3, History, Settings } from 'lucide-react';
import { NavLink } from 'react-router-dom';
import { useTheme } from '@/context/ThemeContext.jsx';

const nav = [{ to: '/', label: 'Dashboard', icon: BarChart3 }, { to: '/history', label: 'History', icon: History }, { to: '/settings', label: 'Settings', icon: Settings }];
export default function Header() {
  const { theme, setTheme, options } = useTheme();
  return <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/90 backdrop-blur dark:border-slate-800 dark:bg-slate-950/90"><div className="mx-auto flex max-w-[1600px] flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6"><NavLink to="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-600 text-white shadow-lg shadow-indigo-600/20"><Activity size={21} aria-hidden="true" /></span><div><div className="text-sm font-semibold tracking-wide">NSE Market Desk</div><div className="text-xs text-slate-500 dark:text-slate-400">Angel One SmartAPI</div></div></NavLink><nav aria-label="Primary" className="order-3 flex w-full items-center justify-center gap-1 rounded-xl border border-slate-200 bg-slate-100 p-1 dark:border-slate-800 dark:bg-slate-900 sm:order-none sm:w-auto">{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} className={({ isActive }) => `flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition ${isActive ? 'bg-white text-indigo-600 shadow-sm dark:bg-slate-800 dark:text-indigo-300' : 'text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-100'}`}><Icon size={16} aria-hidden="true" /><span>{label}</span></NavLink>)}</nav><label className="flex items-center gap-2 text-xs font-medium text-slate-500"><span className="sr-only">Theme</span><select aria-label="Theme" value={theme} onChange={event => setTheme(event.target.value)} className="input w-auto py-2">{options.map(option => <option key={option} value={option}>{option[0].toUpperCase() + option.slice(1)}</option>)}</select></label></div></header>;
}
